### ISSUE TITLE
INVALID_BODY error

### ISSUE THREAD

**Issue by kruu51** [chenwei791129/docker-godaddy-ddns#1]
Hi there,

I am using your docker image and I get this error. A record is updated but the error is there.

Fail! {"code":"INVALID_BODY","message":"Request body doesn't fulfill schema, see details in `fields`"} | stdout
-- | --

**Comment by chenwei791129** [comment]
hi kruu51, seems GoDaddy api got change, i check script from author Nazar78 have update, will follow update to 1.3, thanks your feedback! for now you can try **latest** or **20221123-2d1cfd4** tag to use new script

**Comment by chenwei791129** [comment]
If now other quest, i will close this issue, thanks your feedback.
